import { getAssetPath } from "../../../../utils/assets";

const placeholderPreview = getAssetPath("/modals/placeholder/project-placeholder.webp");

/**
 * Fallback statico dei progetti.
 * Usato SOLO se GitHub API è irraggiungibile, non c'è cache e non c'è connessione.
 * Mantiene lo stesso formato del vecchio projectData.js per compatibilità.
 */
const fallbackProjects = [
    {
        id: "gods-backoffice",
        title: "Gods Backoffice",
        description: "Backend realizzato come esame finale del corso Boolean. Include CRUD completo, gestione API per interazione con front-end, autenticazione Breeze e gestione relazioni DB.",
        preview: placeholderPreview,
        projectScope: "work",
        type: "backend",
        technologies: ["PHP", "Laravel", "Blade", "MySQL", "Breeze", "Bootstrap", "API"],
        repo: "https://github.com/mirkobechini/gods-backoffice",
        live: "#",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "gods-guest-site",
        title: "Gods Guest Site",
        description: "Frontend per esame del corso Boolean permette di consultare le varie mitologie e dei ricevuti tramite chiamate axios a API REST, caratterizzato da design responsive, dark mode e animazioni.",
        preview: placeholderPreview,
        projectScope: "work",
        type: "frontend",
        technologies: ["React", "Axios", "HTML", "CSS", "Bootstrap", "JS"],
        repo: "https://github.com/mirkobechini/gods-guest-site",
        live: "#",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "CV_Backoffice",
        title: "CV Backoffice",
        description: "Gestione flotta mezzi con monitoraggio delle scadenze, gestione di eventuali guasti, log chilometrici, registrazione e gestione dell'equipaggiamento di ogni mezzo.",
        preview: placeholderPreview,
        projectScope: "personal",
        type: "backend",
        technologies: ["PHP", "Laravel", "Blade", "Breeze", "Bootstrap", "MySQL"],
        repo: "https://github.com/mirkobechini/CV_Backoffice",
        live: "#",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "digital-business-card",
        title: "Digital Business Card",
        description: "Biglietto da visita digitale realizzato in React come esercizio del corso React di Scrimba.",
        preview: placeholderPreview,
        projectScope: "personal",
        type: "frontend",
        technologies: ["React", "HTML", "CSS", "Bootstrap", "Vite"],
        repo: "https://github.com/mirkobechini/digital-business-card",
        live: "https://mirkobechini.github.io/digital-business-card/",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "tenzies",
        title: "Tenzies",
        description: "Gioco di dadi realizzato in React come esercizio del corso React di Scrimba.",
        preview: placeholderPreview,
        projectScope: "personal",
        type: "frontend",
        technologies: ["React", "HTML", "CSS", "Vite", "Figma"],
        repo: "https://github.com/mirkobechini/tenzies",
        live: "https://mirkobechini.github.io/tenzies/",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "assembly-endgame",
        title: "Assembly Endgame",
        description: "Sito web per un progetto di gioco da tavolo, realizzato in React come esercizio del corso React di Scrimba.",
        preview: placeholderPreview,
        projectScope: "personal",
        type: "frontend",
        technologies: ["React", "HTML", "CSS", "Vite", "Figma"],
        repo: "https://github.com/mirkobechini/assembly-endgame",
        live: "https://mirkobechini.github.io/assembly-endgame/",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "quizzical",
        title: "Quizzical",
        description: "Quiz interattivo realizzato in React come esercizio del corso React di Scrimba.",
        preview: placeholderPreview,
        projectScope: "personal",
        type: "frontend",
        technologies: ["React", "HTML", "CSS", "Vite", "Figma"],
        repo: "https://github.com/mirkobechini/quizzical",
        live: "https://mirkobechini.github.io/quizzical/",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "mirko-bechini-portfolio",
        title: "Portfolio personale",
        description: "Portfolio personale realizzato in React con Vite, progettato per mostrare il mio percorso e le mie competenze.",
        preview: placeholderPreview,
        projectScope: "personal",
        type: "fullstack",
        technologies: ["React", "HTML", "CSS", "Vite", "Laravel", "JS"],
        repo: "https://github.com/mirkobechini/mirko-bechini-portfolio",
        live: "https://mirkobechini.com/",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "pdfEditor",
        title: "PdfEditor",
        description: "Applicazione cross-platform per la modifica e gestione di file PDF, con funzionalità di visualizzazione, annotazione, conversione, modifica testo e manipolazione avanzata. Architettura modulare che copre web (Next.js), desktop (Tauri v2), mobile (React Native) e backend (FastAPI).",
        preview: placeholderPreview,
        projectScope: "personal",
        type: "fullstack",
        technologies: ["AI", "Next.js", "React Native", "Tauri", "FastAPI", "Python", "TypeScript", "TailwindCSS"],
        repo: "https://github.com/mirkobechini/pdfEditor",
        live: "https://pdfeditor.mirkobechini.com/",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "nasa-neam",
        title: "Nasa - NEAM",
        description: "Webapp per monitorare asteroidi near-Earth usando l'API gratuita NASA NeoWs, con visualizzazioni interattive, alert system e risorse educative. Singolo deploy su Vercel.",
        preview: placeholderPreview,
        projectScope: "personal",
        type: "fullstack",
        technologies: ["AI", "Next.js", "SQLite", "Three.js", "NASA API"],
        repo: "https://github.com/mirkobechini/nasa-neam",
        live: "#",
        stars: 0,
        updatedAt: null,
    },
    {
        id: "agent-skills",
        title: "AI Agent Skills",
        description: "Repo con le varie skill sviluppate per l'AI Agent.",
        preview: placeholderPreview,
        projectScope: "personal",
        type: "fullstack",
        technologies: ["AI", "Python"],
        repo: "https://github.com/mirkobechini/agent-skills",
        live: "#",
        stars: 0,
        updatedAt: null,
    },
];

export default fallbackProjects;